dependencies {
    val kotlin = project.property("kotlinVersion")
    val coroutines = project.property("coroutines")
    val gdx = project.property("gdxVersion")
    val ktx = project.property("ktxVersion")
    val jsonSerialization = project.property("jsonSerialization")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines")
    api("com.badlogicgames.gdx:gdx:$gdx")
    api("org.jetbrains.kotlin:kotlin-stdlib:$kotlin")
    api("com.badlogicgames.gdx:gdx-freetype:$gdx")
    api("io.github.libktx:ktx-collections:$ktx")
    api("io.github.libktx:ktx-assets:$ktx")
    api("io.github.libktx:ktx-async:$ktx")
    api("io.github.libktx:ktx-assets-async:$ktx")
    api("io.github.libktx:ktx-actors:$ktx")
    api("io.github.libktx:ktx-log:$ktx")
    api("io.github.libktx:ktx-i18n:$ktx")
    api("io.github.libktx:ktx-freetype:$ktx")
    api("io.github.libktx:ktx-freetype-async:$ktx")
    api("io.github.libktx:ktx-scene2d:$ktx")
    api("io.github.libktx:ktx-app:$ktx")
    api("io.github.libktx:ktx-math:$ktx")
    api("io.github.libktx:ktx-inject:$ktx")
    api("io.github.libktx:ktx-style:$ktx")
    api("io.github.libktx:ktx-graphics:$ktx")
    api("io.github.libktx:ktx-preferences:$ktx")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$jsonSerialization")
}